language: cpp

dist: trusty

sudo: false

env:
  global:
    - SCONS_CACHE=$HOME/.scons_cache
    - SCONS_CACHE_LIMIT=1024
    - OPTIONS="verbose=yes progress=no gdnative_wrapper=yes"
    - secure: "n/H0YCWDhq3Pl2vOtv8Ai3IltGBHHh9VdL+SENitCBln1N7ygNf17KTEnmBZA+kVCsAVL3M2no8bXDYshlsU5AwxwOC8x3hn+rLmanNkyY3YQiHvCUeduVRbUj+JmirJZGyf/RDifk1mj43ksHlLxDgRnzKEFh5dnXW1neAywU7XKsOOKbvE1+chmCsGeif9/zrn77y+znq0ZTsoy+TDUEXvBSTJsBc6gvyosD7qCf5BHjsv7/g8WkC1hM8C8qwNw9loihDfurQtYLenOffK8duldyqiFiggbRY4RoPGPn6s92Zd30/NNjFsUGMooVj6If3aYHP4oNqToCW4okMIER94Vt4tExlCrkhqClfUM+H/miQYfPNlYH02cGXREwxyKwHBhb5IEjUcLNV9bnW9hQPaTAVkJLRbaTqDjK1wIADgfNPJZ5p8EDnJL9sd6zVCWDEB3Jnf1nxhUkmDOBYRQv/j22m6tgOhZPt00sjwrJbFq8CB5qCgS5KktSN2Tnq9HMkZFFTK7uwYuMm2DMcuwS9B+eQWC0Cdauc2Pf4j4SF0SC6pbKrDyrb3UHM8Zoq+9BFrBiriAhKfZilCmLk38Jc/fkV8DJ/pkz8CUHVbRsSuKjtpvO50kdNIx+2qDcwVWhkRnbQf+gbJ1bvwbT9yfSRGZuTYr86f3XTBfvDFK9c="

cache:
  directories:
    - $SCONS_CACHE

matrix:
  include:
    - env: STATIC_CHECKS=yes
      os: linux
      compiler: clang
    - env: GODOT_TARGET=x11 TOOLS=yes CACHE_NAME=${GODOT_TARGET}-gcc-tools"
      os: linux
      compiler: gcc
    - env: GODOT_TARGET=x11 TOOLS=no CACHE_NAME=${GODOT_TARGET}-clang"
      os: linux
      compiler: clang
    #- env: GODOT_TARGET=windows TOOLS=yes CACHE_NAME=${GODOT_TARGET}-gcc-tools
    #  os: linux
    #  compiler: gcc
    - env: GODOT_TARGET=android TOOLS=no CACHE_NAME=${GODOT_TARGET}-gcc
      os: linux
      compiler: gcc
    - env: GODOT_TARGET=osx TOOLS=yes CACHE_NAME=${GODOT_TARGET}-clang-tools
      os: osx
      osx_image: xcode9.3
      compiler: clang
    - env: GODOT_TARGET=iphone TOOLS=no CACHE_NAME=${GODOT_TARGET}-clang
      os: osx
      osx_image: xcode9.3
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - build-essential
      - scons
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libasound2-dev
      - libfreetype6-dev

      # For cross-compiling to Windows.
      #- binutils-mingw-w64-i686
      #- binutils-mingw-w64-x86-64
      #- gcc-mingw-w64-i686
      #- gcc-mingw-w64-x86-64
      #- g++-mingw-w64-i686
      #- g++-mingw-w64-x86-64
      #- mingw-w64

      # For style checks.
      - clang-format-5.0

  coverity_scan:
    project:
      name: "godotengine/godot"
      description: "Godot Engine Coverity scans"
    notification_email: coverity@godotengine.org
    build_command_prepend: ""
    build_command: "scons p=x11 -j2 $OPTIONS"
    branch_pattern: coverity_scan

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$GODOT_TARGET" = "android" ]; then
      misc/travis/android-tools-linux.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      misc/travis/scons-local-osx.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$GODOT_TARGET" = "android" ]; then
      misc/travis/android-tools-osx.sh;
    fi

before_script:
  - if [ "$GODOT_TARGET" = "android" ]; then
      export ANDROID_HOME=$TRAVIS_BUILD_DIR/godot-dev/build-tools/android-sdk;
      export ANDROID_NDK_ROOT=$TRAVIS_BUILD_DIR/godot-dev/build-tools/android-ndk;
    fi

script:
  - if [ "$STATIC_CHECKS" = "yes" ]; then
      sh ./misc/travis/clang-format.sh;
    else
      scons -j2 CC=$CC CXX=$CXX platform=$GODOT_TARGET TOOLS=$TOOLS $OPTIONS;
    fi
